"""Data note for the translation task.

The headline demo uses a controlled date-translation task whose parallel pairs
are generated deterministically in code (see ``nmt.data.make_date_dataset``), so
no download is required and the results are fully reproducible.

The same encoder-attention-decoder architecture applies unchanged to a natural
language parallel corpus. To use Multi30k, for example, load its
source/target sentence pairs, build character or subword vocabularies the same
way, and pass them through the model; the training loop and BLEU metric do not
change.

Usage:
    python scripts/download_data.py
"""

from __future__ import annotations


def main() -> int:
    print(
        "No download needed: the date-translation pairs are generated by "
        "nmt.data.make_date_dataset. See this script's docstring for how to "
        "swap in a natural-language parallel corpus such as Multi30k."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
